name: acousticnicki
favicon: null
layout_spectrum: 0.3138011659029871
typography_spectrum: 0.26243102294392884
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.30011468776501715
  lightness: 0.9806998358108103
  saturation: 0.3715052723418921
  rhythmicContrast: 0.5189601047895849
purpose: []
